-- Basics on how to create a database and use it
CREATE DATABASE OFFICE;
USE OFFICE;

-- Basics of creating a table and using it
CREATE TABLE EMPLOYEE(
	EMPID INT PRIMARY KEY,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50), 
	AGE INT,  
	DEPT VARCHAR(225)
);


-- Basics of Inserting values inside a Table
INSERT INTO EMPLOYEE(EMPID, FIRSTNAME, LASTNAME, AGE, DEPT)
VALUES
(001, 'SHAHEER', 'JAMAL', 20, 'CYBERSECURITY'), 
(002, 'SAAD', 'IFTIKHAR', 21, 'SALES & MARKETING'), 
(003, 'ABDULLAH', 'NIZAMI', 20, 'BUSINESS DEVELOPMENT'), 
(004, 'FARZAN', 'ANWERY', 21, 'WEB & APP DEVELOPMENT');

INSERT INTO EMPLOYEE(EMPID, FIRSTNAME, LASTNAME, AGE, DEPT)
VALUES
(005, 'MUSFIRAH', 'HARIS', 20, 'CYBERSECURITY')


-- Basic select statement with some filteration
SELECT 
	EMPID, CONCAT(FIRSTNAME, ' ', LASTNAME) EMPLOYEE_NAME, AGE, DEPT 
FROM 
	EMPLOYEE 
WHERE 
	DEPT = 'CYBERSECURITY' AND FIRSTNAME LIKE 'M%'
ORDER BY EMPID;

-- Query to udpate the table
UPDATE EMPLOYEE SET AGE = 24 WHERE EMPID = 002;

-- Truncate statement to empty the table
TRUNCATE TABLE EMPLOYEE;
SELECT * FROM EMPLOYEE;
