-- Distinct (IT IS USED TO REMOVE ALL THE DUPLICATE VALUES FROM THE TABLE - RETURN ALL THE UNIQUE VALUES)

SELECT DISTINCT DEPT FROM EMPLOYEE;
SELECT  DISTINCT CONCAT(FIRSTNAME, ' ', LASTNAME) AS EMP_NAME FROM EMPLOYEE;

-- NULL QUERY (CAN BE USED IN BOTH WAY| NULL AND NOT NULL)
SELECT * FROM EMPLOYEE WHERE AGE IS NOT NULL;

-- BETWEEN QUERY (SELECT THE VALUE BETWEEN THE GIVEN RANGE)
SELECT * FROM EMPLOYEE WHERE DEPT = 'Data Engineering' AND AGE BETWEEN 25 AND 30 ORDER BY AGE;

-- LIKE QUERY (WILDCARDS WE CAN SAY)
SELECT * FROM EMPLOYEE WHERE DEPT = 'Customer Success' AND LASTNAME LIKE 'B%'; --This will include all the values which initial is B
SELECT * FROM EMPLOYEE WHERE DEPT = 'Customer Success' AND LASTNAME LIKE '_u%'; -- This will include all those values which have U as a second alphabet in their lastname
SELECT * FROM EMPLOYEE WHERE DEPT = 'Customer Success' AND FIRSTNAME LIKE '[ABC]%' ORDER BY FIRSTNAME; -- This will include only those values which have ABC as an initials in their firstname
SELECT * FROM EMPLOYEE WHERE DEPT = 'Data Engineering' AND FIRSTNAME LIKE '[^A-I]%' AND AGE < 30 ORDER BY FIRSTNAME; -- This will exclude all those values which firstname initials are in the range of A-I

-- AGGREGATE FUNCTIONS (COUNT, SUM, MAX, MIN ETC)
SELECT COUNT(EMPID) AS TOTAL_EMPLOYEE FROM EMPLOYEE WHERE DEPT = 'Data Engineering'; 
SELECT AVG(AGE) AS AVERAGE_AGE_DE FROM EMPLOYEE WHERE DEPT = 'Data Engineering'; 
SELECT AVG(AGE) AS AVERAGE_AGE_CS FROM EMPLOYEE WHERE DEPT = 'Customer Success'; 
SELECT AVG(AGE) AS AVERAGE_AGE_CC FROM EMPLOYEE WHERE DEPT = 'Leadership'; 

