-- SET OPERATORS(UNION, INTERSECT, EXCEPT)

SELECT COUNT(EMPID) Total_DE FROM EMPLOYEE WHERE DEPT = 'Data Engineering'
UNION
SELECT COUNT(EMPID) Total_CS FROM EMPLOYEE WHERE DEPT = 'Customer Success'
